(() => {
  'use strict';
  const SIZE=8, COLORS=['#ff7f72','#ffc866','#72d8f2','#b784f7','#69e3bd'], CODE_CHARS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const SHAPES=[[[0,0]],[[0,0],[0,1]],[[0,0],[1,0]],[[0,0],[0,1],[0,2]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[1,0],[1,1]],[[0,0],[1,0],[1,1]],[[0,0],[0,1],[1,1]],[[0,0],[1,0],[2,0],[2,1]],[[0,1],[1,1],[2,0],[2,1]],[[0,0],[0,1],[0,2],[0,3]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[0,2],[1,0],[1,1],[1,2]],[[0,0],[0,1],[1,0],[1,1],[2,0],[2,1]],[[0,0],[0,1],[0,2],[1,1]],[[0,1],[1,0],[1,1],[1,2]],[[0,0],[0,1],[0,2],[1,0],[2,0]],[[0,0],[1,0],[2,0],[2,1],[2,2]],[[0,0],[0,1],[0,2],[1,0],[1,1],[1,2],[2,0],[2,1],[2,2]]];
  const $=s=>document.querySelector(s);
  const els={home:$('#home'),game:$('#game'),board:$('#board'),opponentBoard:$('#opponentBoard'),boardsStage:$('#boardsStage'),opponentPanel:$('#opponentPanel'),yourCaption:$('#yourCaption'),opponentScore:$('#opponentScore'),yourScore:$('#yourScore'),tray:$('#tray'),score:$('#score'),combo:$('#combo'),middleLabel:$('#middleLabel'),best:$('#best'),modeLabel:$('#modeLabel'),turnLabel:$('#turnLabel'),playerStrip:$('#playerStrip'),playerOne:$('#playerOne'),playerTwo:$('#playerTwo'),toast:$('#toast'),modal:$('#modal'),deselect:$('#deselect'),onlineModal:$('#onlineModal'),onlineError:$('#onlineError'),onlineStart:$('#onlineStart'),roomCodeField:$('#roomCodeField'),roomCodeInput:$('#roomCodeInput'),roomStatus:$('#roomStatus'),roomStatusText:$('#roomStatusText')};
  let state,onlineAction='create',firebasePromise=null,onlineSession=null,dragState=null,suppressClickUntil=0;
  const blankBoard=()=>Array.from({length:SIZE},()=>Array(SIZE).fill(0));
  const bestKey=()=>`mosaic-mates-best-${state?.mode||'solo'}`;
  function seeded(seed){let x=seed|0;return()=>{x=(x*1664525+1013904223)|0;return(x>>>0)/4294967296;};}
  function makeTray(seed=null,trayNumber=0){const rand=seed===null?Math.random:seeded(seed+trayNumber*7919);return[0,1,2].map(i=>({id:`${trayNumber}-${i}`,shape:SHAPES[Math.floor(rand()*SHAPES.length)],color:COLORS[Math.floor(rand()*COLORS.length)],used:false}));}
  function newOnlineState(seed=Math.floor(Math.random()*2147483647)){return{mode:'online',boards:[blankBoard(),blankBoard()],trayNumbers:[0,0],trays:[makeTray(seed,0),makeTray(seed,0)],playerScores:[0,0],combos:[0,0],clearsSinceMiss:[0,0],over:[false,false],seed,selected:null};}
  function newState(mode,seed=Math.floor(Math.random()*2147483647)){if(mode==='online')return newOnlineState(seed);return{mode,board:blankBoard(),trayNumber:0,tray:makeTray(null,0),selected:null,score:0,combo:0,clearsSinceMiss:0,turn:0,playerScores:[0,0],seed,over:false};}
  function normalizeState(raw){if(raw?.mode==='online'&&raw?.boards){const base=newOnlineState(raw.seed||1),s={...base,...raw};s.boards=[0,1].map(p=>Array.from({length:SIZE},(_,r)=>Array.from({length:SIZE},(_,c)=>raw?.boards?.[p]?.[r]?.[c]||0)));s.trays=[0,1].map(p=>(raw?.trays?.[p]||base.trays[p]).map(piece=>({...piece,used:Boolean(piece.used)})));s.trayNumbers=[Number(raw?.trayNumbers?.[0]||0),Number(raw?.trayNumbers?.[1]||0)];s.playerScores=[Number(raw?.playerScores?.[0]||0),Number(raw?.playerScores?.[1]||0)];s.combos=[Number(raw?.combos?.[0]||0),Number(raw?.combos?.[1]||0)];s.clearsSinceMiss=[Number(raw?.clearsSinceMiss?.[0]||0),Number(raw?.clearsSinceMiss?.[1]||0)];s.over=[Boolean(raw?.over?.[0]),Boolean(raw?.over?.[1])];s.selected=null;return s;}const base=newState(raw?.mode||'solo',raw?.seed||1),s={...base,...raw};s.board=Array.from({length:SIZE},(_,r)=>Array.from({length:SIZE},(_,c)=>raw?.board?.[r]?.[c]||0));s.tray=(raw?.tray||base.tray).map(p=>({...p,used:Boolean(p.used)}));s.playerScores=[Number(raw?.playerScores?.[0]||0),Number(raw?.playerScores?.[1]||0)];s.selected=null;return s;}
  function playerIndex(){return onlineSession?.playerIndex||0;} function activeBoard(s=state){return s.mode==='online'?s.boards[playerIndex()]:s.board;} function activeTray(s=state){return s.mode==='online'?s.trays[playerIndex()]:s.tray;}
  function start(mode,initial=null){state=initial||newState(mode);els.home.classList.remove('active');els.game.classList.add('active');els.modal.classList.remove('open');els.onlineModal.classList.remove('open');const names={solo:['Solo Mosaic','Your move'],coop:['Shared Mosaic','George’s turn'],race:['Score Race','George’s turn'],online:['Live Score Race','Waiting for player two']};els.modeLabel.textContent=names[mode][0];els.turnLabel.textContent=names[mode][1];els.playerStrip.classList.toggle('hidden',mode==='solo'||mode==='online');$('.versus').textContent=mode==='coop'?'together':'versus';els.roomStatus.classList.toggle('hidden',mode!=='online');els.boardsStage.classList.toggle('online',mode==='online');els.opponentPanel.classList.toggle('hidden',mode!=='online');els.yourCaption.classList.toggle('hidden',mode!=='online');els.middleLabel.textContent=mode==='online'?'Time':'Glow';render();}
  function pieceBounds(piece){return{rows:Math.max(...piece.shape.map(p=>p[0]))+1,cols:Math.max(...piece.shape.map(p=>p[1]))+1};}
  function resolveAnchor(piece,aimRow,aimCol){const {rows,cols}=pieceBounds(piece);return{row:Math.max(0,Math.min(SIZE-rows,aimRow-Math.floor(rows/2))),col:Math.max(0,Math.min(SIZE-cols,aimCol-Math.floor(cols/2)))};}
  function canPlace(s,piece,row,col){return piece.shape.every(([r,c])=>row+r<SIZE&&col+c<SIZE&&row+r>=0&&col+c>=0&&!s.board[row+r][col+c]);}
  function anyMove(s){return s.tray.some(p=>!p.used&&Array.from({length:SIZE},(_,r)=>r).some(r=>Array.from({length:SIZE},(_,c)=>c).some(c=>canPlace(s,p,r,c))));}
  function clearLines(s){const rows=[],cols=[];for(let r=0;r<SIZE;r++)if(s.board[r].every(Boolean))rows.push(r);for(let c=0;c<SIZE;c++)if(s.board.every(row=>row[c]))cols.push(c);rows.forEach(r=>s.board[r].fill(0));cols.forEach(c=>s.board.forEach(row=>row[c]=0));return rows.length+cols.length;}
  function applyMove(s,pieceIndex,row,col){const piece=s.tray[pieceIndex];if(!piece||piece.used||!canPlace(s,piece,row,col))return null;piece.shape.forEach(([r,c])=>s.board[row+r][col+c]=piece.color);piece.used=true;s.score+=piece.shape.length;s.playerScores[s.turn]+=piece.shape.length;const cleared=clearLines(s);if(cleared){s.combo+=1;s.clearsSinceMiss=0;const bonus=cleared*12*s.combo;s.score+=bonus;s.playerScores[s.turn]+=bonus;}else{s.clearsSinceMiss+=1;if(s.clearsSinceMiss>=3)s.combo=0;}s.turn=1-s.turn;if(s.tray.every(p=>p.used)){s.trayNumber+=1;s.tray=makeTray(s.mode==='online'?s.seed:null,s.trayNumber);}s.over=!anyMove(s);return{cleared};}
  function applyOnlineMove(s,p,pieceIndex,row,col){const board=s.boards[p],tray=s.trays[p],piece=tray[pieceIndex],view={board};if(!piece||piece.used||s.over[p]||!canPlace(view,piece,row,col))return null;piece.shape.forEach(([r,c])=>board[row+r][col+c]=piece.color);piece.used=true;s.playerScores[p]+=piece.shape.length;const cleared=clearLines(view);if(cleared){s.combos[p]+=1;s.clearsSinceMiss[p]=0;s.playerScores[p]+=cleared*12*s.combos[p];}else{s.clearsSinceMiss[p]+=1;if(s.clearsSinceMiss[p]>=3)s.combos[p]=0;}if(tray.every(item=>item.used)){s.trayNumbers[p]+=1;s.trays[p]=makeTray(s.seed,s.trayNumbers[p]);}s.over[p]=!anyMove({board:s.boards[p],tray:s.trays[p]});return{cleared};}
  async function place(aimRow,aimCol){const tray=activeTray(),piece=tray[state.selected];if(!piece||piece.used)return;const {row,col}=resolveAnchor(piece,aimRow,aimCol),view={board:activeBoard()};if(state.mode==='online'){if(onlineSession?.status!=='playing'||onlineSession.remainingMs<=0){showToast(onlineSession?.status==='waiting'?'Waiting for player two…':'Race finished');return;}if(!canPlace(view,piece,row,col)){flashInvalid(piece,row,col);return;}const index=state.selected,p=playerIndex();state.selected=null;await onlineSession.firebase.databaseApi.runTransaction(onlineSession.firebase.databaseApi.child(onlineSession.roomRef,'state'),current=>{if(!current)return current;const next=normalizeState(current);return applyOnlineMove(next,p,index,row,col)?serializable(next):undefined;});return;}if(!canPlace(view,piece,row,col)){flashInvalid(piece,row,col);return;}const result=applyMove(state,state.selected,row,col);state.selected=null;if(result.cleared)showToast(result.cleared>1?`${result.cleared} lines glow`:'Line glow');saveBest();render();if(state.over)endGame();}
  function serializable(s){if(s.mode==='online')return{mode:s.mode,boards:s.boards,trayNumbers:s.trayNumbers,trays:s.trays,playerScores:s.playerScores,combos:s.combos,clearsSinceMiss:s.clearsSinceMiss,seed:s.seed,over:s.over};return{mode:s.mode,board:s.board,trayNumber:s.trayNumber,tray:s.tray,score:s.score,combo:s.combo,clearsSinceMiss:s.clearsSinceMiss,turn:s.turn,playerScores:s.playerScores,seed:s.seed,over:s.over};}
  function render(){renderBoard();renderTray();const online=state.mode==='online',p=playerIndex(),score=online?state.playerScores[p]:state.score;els.score.textContent=score.toLocaleString();els.combo.textContent=online?formatTime(onlineSession?.remainingMs??180000):(state.combo?`×${state.combo}`:'—');els.best.textContent=Math.max(score,Number(localStorage.getItem(bestKey())||0)).toLocaleString();els.deselect.classList.toggle('hidden',state.selected===null);if(online){const other=1-p;els.opponentScore.textContent=state.playerScores[other];els.yourScore.textContent=state.playerScores[p];els.turnLabel.textContent=onlineSession?.status==='waiting'?'Waiting for player two':'Race in progress';renderOpponentBoard(state.boards[other]);}else if(state.mode!=='solo'){els.playerOne.classList.toggle('active',state.turn===0);els.playerTwo.classList.toggle('active',state.turn===1);els.playerOne.querySelector('b').textContent=state.playerScores[0];els.playerTwo.querySelector('b').textContent=state.playerScores[1];els.turnLabel.textContent=`${state.turn?'Megan':'George'}’s turn`;}}
  function paintBoard(container,board,interactive=false){container.innerHTML='';for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const cell=document.createElement(interactive?'button':'i');cell.className='cell';if(interactive)cell.setAttribute('role','gridcell');if(board[r][c]){cell.classList.add('filled');cell.style.setProperty('--cell-color',board[r][c]);}if(interactive){cell.addEventListener('click',()=>place(r,c));cell.addEventListener('pointerdown',()=>preview(r,c));cell.addEventListener('pointerenter',()=>preview(r,c));}container.appendChild(cell);}}
  function renderBoard(){paintBoard(els.board,activeBoard(),true);} function renderOpponentBoard(board){paintBoard(els.opponentBoard,board,false);}
  function renderTray(){els.tray.innerHTML='';activeTray().forEach((piece,i)=>{const button=document.createElement('button');button.className='piece';button.style.setProperty('--piece-color',piece.color);button.setAttribute('aria-label',`Shape ${i+1}`);if(piece.used)button.classList.add('used');if(state.selected===i)button.classList.add('selected');const {rows,cols}=pieceBounds(piece),grid=document.createElement('span');grid.className='mini-grid';grid.style.gridTemplateColumns=`repeat(${cols},1fr)`;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const dot=document.createElement('i');dot.className='mini-cell';if(piece.shape.some(p=>p[0]===r&&p[1]===c))dot.classList.add('on');grid.appendChild(dot);}button.appendChild(grid);button.addEventListener('click',event=>{if(piece.used||dragState||performance.now()<suppressClickUntil)return;if(event.detail===0){state.selected=state.selected===i?null:i;render();}});button.addEventListener('pointerdown',event=>beginDrag(event,i,button));els.tray.appendChild(button);});}
  const cellAt=(r,c)=>els.board.children[r*SIZE+c];
  function clearPreview(){els.board.querySelectorAll('.cell.preview,.cell.blocked-preview').forEach(cell=>cell.classList.remove('preview','blocked-preview'));}
  function preview(aimRow,aimCol){clearPreview();const piece=activeTray()[state.selected];if(!piece)return false;const {row,col}=resolveAnchor(piece,aimRow,aimCol),view={board:activeBoard()},valid=canPlace(view,piece,row,col);piece.shape.forEach(([r,c])=>{const cell=cellAt(row+r,col+c);cell.classList.add(valid?'preview':'blocked-preview');cell.style.setProperty('--piece-color',piece.color);});return valid;}
  function flashInvalid(piece,row,col){piece.shape.forEach(([r,c])=>{if(row+r<SIZE&&col+c<SIZE){const cell=cellAt(row+r,col+c);cell.classList.add('invalid');setTimeout(()=>cell.classList.remove('invalid'),450);}});if(navigator.vibrate)navigator.vibrate(25);}
  function showToast(text){els.toast.textContent=text;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),900);}
  function saveBest(){const score=state.mode==='online'?state.playerScores[playerIndex()]:state.score,key=bestKey();if(score>Number(localStorage.getItem(key)||0))localStorage.setItem(key,score);}
  function boardGeometry(){const cells=[...els.board.children],rect=els.board.getBoundingClientRect(),boxes=cells.map(cell=>cell.getBoundingClientRect()),first=boxes[0],next=boxes[1];return{rect,centers:boxes.map(box=>({x:box.left+box.width/2,y:box.top+box.height/2})),cellWidth:first?.width||rect.width/SIZE,cellHeight:first?.height||rect.height/SIZE,gap:next&&first?Math.max(0,next.left-first.right):0};}
  function pointToCell(x,y,geometry=dragState?.geometry||boardGeometry()){const margin=Math.max(18,geometry.cellWidth*.45),{rect,centers}=geometry;if(x<rect.left-margin||x>rect.right+margin||y<rect.top-margin||y>rect.bottom+margin)return null;let bestIndex=0,bestDistance=Infinity;centers.forEach((center,index)=>{const dx=x-center.x,dy=y-center.y,distance=dx*dx+dy*dy;if(distance<bestDistance){bestDistance=distance;bestIndex=index;}});return{row:Math.floor(bestIndex/SIZE),col:bestIndex%SIZE};}
  function dragLift(pointerType,piece,geometry){if(pointerType==='mouse')return 0;const {rows}=pieceBounds(piece),halfShape=(rows*geometry.cellHeight+(rows-1)*geometry.gap)/2;return pointerType==='touch'?halfShape+34:Math.max(26,halfShape+12);}
  function beginDrag(event,index,button){if(event.isPrimary===false||(event.pointerType==='mouse'&&event.button!==0))return;const piece=activeTray()[index];if(!piece||piece.used||dragState)return;event.preventDefault();const wasSelected=state.selected===index,geometry=boardGeometry();state.selected=index;try{button.setPointerCapture(event.pointerId);}catch{}dragState={pointerId:event.pointerId,index,wasSelected,source:button,startX:event.clientX,startY:event.clientY,lift:dragLift(event.pointerType,piece,geometry),geometry,dragging:false,ghost:null,cell:null,valid:false};document.addEventListener('pointermove',moveDrag,{passive:false,capture:true});document.addEventListener('pointerup',endDrag,{capture:true});document.addEventListener('pointercancel',cancelDrag,{capture:true});}
  function startDragVisual(){const piece=activeTray()[dragState.index],ghost=document.createElement('div'),grid=dragState.source.querySelector('.mini-grid').cloneNode(true);ghost.className='drag-ghost';ghost.style.setProperty('--piece-color',piece.color);ghost.style.setProperty('--drag-cell',`${dragState.geometry.cellWidth}px`);ghost.style.setProperty('--drag-gap',`${dragState.geometry.gap}px`);ghost.appendChild(grid);document.body.appendChild(ghost);dragState.ghost=ghost;dragState.dragging=true;dragState.source.classList.add('dragging');document.body.classList.add('is-dragging');}
  function updateDragTarget(x,y){dragState.ghost.style.left=`${x}px`;dragState.ghost.style.top=`${y}px`;dragState.cell=pointToCell(x,y);dragState.valid=dragState.cell?preview(dragState.cell.row,dragState.cell.col):false;els.board.classList.toggle('drag-valid',Boolean(dragState.cell&&dragState.valid));els.board.classList.toggle('drag-invalid',Boolean(dragState.cell&&!dragState.valid));if(!dragState.cell)clearPreview();}
  function moveDrag(event){if(!dragState||event.pointerId!==dragState.pointerId)return;event.preventDefault();if(!dragState.dragging&&Math.hypot(event.clientX-dragState.startX,event.clientY-dragState.startY)<7)return;if(!dragState.dragging)startDragVisual();updateDragTarget(event.clientX,event.clientY-dragState.lift);}
  function finishDrag(){const finished=dragState;if(!finished)return null;finished.ghost?.remove();finished.source?.classList.remove('dragging');try{if(finished.source?.hasPointerCapture(finished.pointerId))finished.source.releasePointerCapture(finished.pointerId);}catch{}dragState=null;suppressClickUntil=performance.now()+450;document.body.classList.remove('is-dragging');els.board.classList.remove('drag-valid','drag-invalid');document.removeEventListener('pointermove',moveDrag,true);document.removeEventListener('pointerup',endDrag,true);document.removeEventListener('pointercancel',cancelDrag,true);clearPreview();return finished;}
  function endDrag(event){if(!dragState||event.pointerId!==dragState.pointerId)return;event.preventDefault();if(dragState.dragging)updateDragTarget(event.clientX,event.clientY-dragState.lift);const finished=finishDrag();if(!finished)return;if(finished.dragging){if(finished.cell&&finished.valid)place(finished.cell.row,finished.cell.col);else if(finished.cell){const piece=activeTray()[finished.index],anchor=resolveAnchor(piece,finished.cell.row,finished.cell.col);flashInvalid(piece,anchor.row,anchor.col);state.selected=null;setTimeout(render,470);}else{state.selected=null;render();}}else{state.selected=finished.wasSelected?null:finished.index;render();}}
  function cancelDrag(event){if(event&&dragState&&event.pointerId!==dragState.pointerId)return;finishDrag();state.selected=null;render();}
  function formatTime(ms){const total=Math.max(0,Math.ceil(ms/1000));return`${Math.floor(total/60)}:${String(total%60).padStart(2,'0')}`;}
  function updateTimer(){if(!onlineSession||onlineSession.status!=='playing'||!onlineSession.startsAt)return;onlineSession.remainingMs=Math.max(0,onlineSession.durationMs-(Date.now()-onlineSession.startsAt));els.combo.textContent=formatTime(onlineSession.remainingMs);if(onlineSession.remainingMs<=0&&!onlineSession.endedShown){onlineSession.endedShown=true;endGame();}}
  function endGame(){saveBest();$('#modalEyebrow').textContent=state.mode==='online'?'Time is up':'Board complete';const scores=state.playerScores||[0,0];$('#modalTitle').textContent=(state.mode==='race'||state.mode==='online')?(scores[0]===scores[1]?'Perfect tie':`${scores[0]>scores[1]?'George':'Megan'} wins`):'Beautifully played';$('#modalBody').textContent=(state.mode==='race'||state.mode==='online')?`Final score: ${scores[0]}–${scores[1]}.`:`You built a score of ${state.score.toLocaleString()}.`;els.modal.classList.add('open');}
  function leaveOnline(){onlineSession?.unsubscribe?.();clearInterval(onlineSession?.timerId);onlineSession=null;history.replaceState(null,'',location.pathname);}
  function goHome(){leaveOnline();els.game.classList.remove('active');els.home.classList.add('active');els.modal.classList.remove('open');}
  function roomCode(){return Array.from({length:6},()=>CODE_CHARS[Math.floor(Math.random()*CODE_CHARS.length)]).join('');}
  function normalizeCode(value){return value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);}
  async function loadFirebase(){const config=window.MOSAIC_FIREBASE_CONFIG;if(!config)throw new Error('Online rooms are built but the dedicated Firebase project still needs connecting.');if(!firebasePromise)firebasePromise=Promise.all([import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js')]).then(([appApi,authApi,databaseApi])=>{const app=appApi.initializeApp(config);return{authApi,databaseApi,auth:authApi.getAuth(app),db:databaseApi.getDatabase(app)};});const firebase=await firebasePromise;if(!firebase.auth.currentUser)await firebase.authApi.signInAnonymously(firebase.auth);return firebase;}
  async function createRoom(){const firebase=await loadFirebase();let code,ref;for(let tries=0;tries<8;tries++){code=roomCode();ref=firebase.databaseApi.ref(firebase.db,`rooms/${code}`);if(!(await firebase.databaseApi.get(ref)).exists())break;}const initial=newState('online');await firebase.databaseApi.set(ref,{hostUid:firebase.auth.currentUser.uid,status:'waiting',createdAt:firebase.databaseApi.serverTimestamp(),durationMs:180000,state:serializable(initial)});beginOnline(firebase,ref,code,0,'waiting',initial);}
  async function joinRoom(){const code=normalizeCode(els.roomCodeInput.value);if(code.length!==6)throw new Error('Enter the six-character code from the other iPad.');const firebase=await loadFirebase(),ref=firebase.databaseApi.ref(firebase.db,`rooms/${code}`),snap=await firebase.databaseApi.get(ref);if(!snap.exists())throw new Error('That room could not be found.');const room=snap.val();if(room.status!=='waiting'||room.guestUid)throw new Error('That room already has two players.');await firebase.databaseApi.set(firebase.databaseApi.child(ref,'guestUid'),firebase.auth.currentUser.uid);await firebase.databaseApi.update(ref,{status:'playing',startsAt:firebase.databaseApi.serverTimestamp()});beginOnline(firebase,ref,code,1,'playing',normalizeState(room.state));}
  function beginOnline(firebase,roomRef,code,p,status,initial){onlineSession?.unsubscribe?.();clearInterval(onlineSession?.timerId);onlineSession={firebase,roomRef,code,playerIndex:p,status,remainingMs:180000,durationMs:180000,startsAt:null,endedShown:false,unsubscribe:null,timerId:null};history.replaceState(null,'',`${location.pathname}?room=${code}`);start('online',normalizeState(initial));onlineSession.timerId=setInterval(updateTimer,250);onlineSession.unsubscribe=firebase.databaseApi.onValue(roomRef,snap=>{if(!snap.exists()){els.roomStatusText.textContent='Room closed';return;}const room=snap.val(),dragging=Boolean(dragState),selected=dragState?.index;onlineSession.status=room.status;onlineSession.durationMs=room.durationMs||180000;onlineSession.startsAt=room.startsAt||null;state=normalizeState(room.state);if(dragging)state.selected=selected;els.roomStatusText.textContent=room.status==='waiting'?`ROOM ${code} · Waiting for player two…`:`ROOM ${code} · Live score race`;updateTimer();if(dragging){const other=1-playerIndex();els.opponentScore.textContent=state.playerScores[other];els.yourScore.textContent=state.playerScores[playerIndex()];renderOpponentBoard(state.boards[other]);}else render();});}
  function inviteUrl(){return onlineSession?`${location.origin}${location.pathname}?room=${onlineSession.code}`:location.href;}
  async function copyInvite(){if(!onlineSession)return;await navigator.clipboard.writeText(onlineSession.code);showToast('Room code copied');}
  async function shareInvite(){if(!onlineSession)return;const data={title:'Join my Mosaic Mates room',text:`Join my Mosaic Mates room ${onlineSession.code}`,url:inviteUrl()};if(navigator.share){try{await navigator.share(data);return;}catch(error){if(error?.name==='AbortError')return;}}try{await navigator.clipboard.writeText(inviteUrl());showToast('Invite link copied');}catch{showToast('Could not share this invite');}}
  function setOnlineAction(action){onlineAction=action;document.querySelectorAll('[data-online-action]').forEach(b=>b.classList.toggle('active',b.dataset.onlineAction===action));els.roomCodeField.classList.toggle('hidden',action!=='join');els.onlineStart.textContent=action==='join'?'Join private room':'Create private room';els.onlineError.textContent='';}
  document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mode)));$('#backButton').addEventListener('click',goHome);$('#restartButton').addEventListener('click',()=>state.mode==='online'?showToast('Online rematch comes next'):start(state.mode));$('#playAgain').addEventListener('click',()=>start(state.mode));$('#modalHome').addEventListener('click',goHome);els.deselect.addEventListener('click',()=>{state.selected=null;render();});els.board.addEventListener('pointerleave',clearPreview);
  $('#onlinePreview').addEventListener('click',()=>{els.onlineModal.classList.add('open');els.onlineModal.setAttribute('aria-hidden','false');setOnlineAction('create');});$('#closeOnline').addEventListener('click',()=>els.onlineModal.classList.remove('open'));document.querySelectorAll('[data-online-action]').forEach(b=>b.addEventListener('click',()=>setOnlineAction(b.dataset.onlineAction)));els.roomCodeInput.addEventListener('input',()=>els.roomCodeInput.value=normalizeCode(els.roomCodeInput.value));els.onlineStart.addEventListener('click',async()=>{els.onlineError.textContent='';els.onlineStart.disabled=true;els.onlineStart.textContent='Connecting…';try{if(onlineAction==='create')await createRoom();else await joinRoom();}catch(error){els.onlineError.textContent=error.message;setOnlineAction(onlineAction);}finally{els.onlineStart.disabled=false;}});$('#copyRoomCode').addEventListener('click',copyInvite);$('#shareRoom').addEventListener('click',shareInvite);
  const linked=normalizeCode(new URLSearchParams(location.search).get('room')||'');if(linked){els.onlineModal.classList.add('open');setOnlineAction('join');els.roomCodeInput.value=linked;}if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
})();
