(() => {
  'use strict';
  const SIZE=8, COLORS=['#ff7f72','#ffc866','#72d8f2','#b784f7','#69e3bd'], CODE_CHARS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const SHAPES=[[[0,0]],[[0,0],[0,1]],[[0,0],[1,0]],[[0,0],[0,1],[0,2]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[1,0],[1,1]],[[0,0],[1,0],[1,1]],[[0,0],[0,1],[1,1]],[[0,0],[1,0],[2,0],[2,1]],[[0,1],[1,1],[2,0],[2,1]],[[0,0],[0,1],[0,2],[0,3]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[0,2],[1,0],[1,1],[1,2]],[[0,0],[0,1],[1,0],[1,1],[2,0],[2,1]],[[0,0],[0,1],[0,2],[1,1]],[[0,1],[1,0],[1,1],[1,2]],[[0,0],[0,1],[0,2],[1,0],[2,0]],[[0,0],[1,0],[2,0],[2,1],[2,2]],[[0,0],[0,1],[0,2],[1,0],[1,1],[1,2],[2,0],[2,1],[2,2]]];
  const $=s=>document.querySelector(s);
  const els={home:$('#home'),game:$('#game'),board:$('#board'),tray:$('#tray'),score:$('#score'),combo:$('#combo'),best:$('#best'),modeLabel:$('#modeLabel'),turnLabel:$('#turnLabel'),playerStrip:$('#playerStrip'),playerOne:$('#playerOne'),playerTwo:$('#playerTwo'),toast:$('#toast'),modal:$('#modal'),deselect:$('#deselect'),onlineModal:$('#onlineModal'),onlineError:$('#onlineError'),onlineStart:$('#onlineStart'),roomCodeField:$('#roomCodeField'),roomCodeInput:$('#roomCodeInput'),roomStatus:$('#roomStatus'),roomStatusText:$('#roomStatusText')};
  let state,onlineAction='create',firebasePromise=null,onlineSession=null;
  const blankBoard=()=>Array.from({length:SIZE},()=>Array(SIZE).fill(0));
  const bestKey=()=>`mosaic-mates-best-${state?.mode||'solo'}`;
  function seeded(seed){let x=seed|0;return()=>{x=(x*1664525+1013904223)|0;return(x>>>0)/4294967296;};}
  function makeTray(seed=null,trayNumber=0){const rand=seed===null?Math.random:seeded(seed+trayNumber*7919);return[0,1,2].map(i=>({id:`${trayNumber}-${i}`,shape:SHAPES[Math.floor(rand()*SHAPES.length)],color:COLORS[Math.floor(rand()*COLORS.length)],used:false}));}
  function newState(mode,seed=Math.floor(Math.random()*2147483647)){return{mode,board:blankBoard(),trayNumber:0,tray:makeTray(mode==='online'?seed:null,0),selected:null,score:0,combo:0,clearsSinceMiss:0,turn:0,playerScores:[0,0],seed,over:false};}
  function normalizeState(raw){const base=newState(raw?.mode||'online',raw?.seed||1),s={...base,...raw};s.board=Array.from({length:SIZE},(_,r)=>Array.from({length:SIZE},(_,c)=>raw?.board?.[r]?.[c]||0));s.tray=(raw?.tray||base.tray).map(p=>({...p,used:Boolean(p.used)}));s.playerScores=[Number(raw?.playerScores?.[0]||0),Number(raw?.playerScores?.[1]||0)];s.selected=null;return s;}
  function start(mode,initial=null){state=initial||newState(mode);els.home.classList.remove('active');els.game.classList.add('active');els.modal.classList.remove('open');els.onlineModal.classList.remove('open');const names={solo:['Solo Mosaic','Your move'],coop:['Shared Mosaic','George’s turn'],race:['Score Race','George’s turn'],online:['Two iPads','Room ready']};els.modeLabel.textContent=names[mode][0];els.turnLabel.textContent=names[mode][1];els.playerStrip.classList.toggle('hidden',mode==='solo');$('.versus').textContent=mode==='coop'?'together':'versus';els.roomStatus.classList.toggle('hidden',mode!=='online');render();}
  function canPlace(s,piece,row,col){return piece.shape.every(([r,c])=>row+r<SIZE&&col+c<SIZE&&row+r>=0&&col+c>=0&&!s.board[row+r][col+c]);}
  function anyMove(s){return s.tray.some(p=>!p.used&&Array.from({length:SIZE},(_,r)=>r).some(r=>Array.from({length:SIZE},(_,c)=>c).some(c=>canPlace(s,p,r,c))));}
  function clearLines(s){const rows=[],cols=[];for(let r=0;r<SIZE;r++)if(s.board[r].every(Boolean))rows.push(r);for(let c=0;c<SIZE;c++)if(s.board.every(row=>row[c]))cols.push(c);rows.forEach(r=>s.board[r].fill(0));cols.forEach(c=>s.board.forEach(row=>row[c]=0));return rows.length+cols.length;}
  function applyMove(s,pieceIndex,row,col){const piece=s.tray[pieceIndex];if(!piece||piece.used||!canPlace(s,piece,row,col))return null;piece.shape.forEach(([r,c])=>s.board[row+r][col+c]=piece.color);piece.used=true;s.score+=piece.shape.length;s.playerScores[s.turn]+=piece.shape.length;const cleared=clearLines(s);if(cleared){s.combo+=1;s.clearsSinceMiss=0;const bonus=cleared*12*s.combo;s.score+=bonus;s.playerScores[s.turn]+=bonus;}else{s.clearsSinceMiss+=1;if(s.clearsSinceMiss>=3)s.combo=0;}s.turn=1-s.turn;if(s.tray.every(p=>p.used)){s.trayNumber+=1;s.tray=makeTray(s.mode==='online'?s.seed:null,s.trayNumber);}s.over=!anyMove(s);return{cleared};}
  async function place(row,col){const piece=state.tray[state.selected];if(!piece||piece.used)return;if(state.mode==='online'){if(onlineSession?.status!=='playing'||state.turn!==onlineSession.playerIndex){showToast(onlineSession?.status==='waiting'?'Waiting for Megan…':'Their turn');return;}if(!canPlace(state,piece,row,col)){flashInvalid(piece,row,col);return;}const index=state.selected;state.selected=null;await onlineSession.firebase.databaseApi.runTransaction(onlineSession.firebase.databaseApi.child(onlineSession.roomRef,'state'),current=>{if(!current)return current;const next=normalizeState(current);if(next.turn!==onlineSession.playerIndex||next.over)return;return applyMove(next,index,row,col)?serializable(next):undefined;});return;}if(!canPlace(state,piece,row,col)){flashInvalid(piece,row,col);return;}const result=applyMove(state,state.selected,row,col);state.selected=null;if(result.cleared)showToast(result.cleared>1?`${result.cleared} lines glow`:'Line glow');saveBest();render();if(state.over)endGame();}
  function serializable(s){return{mode:s.mode,board:s.board,trayNumber:s.trayNumber,tray:s.tray,score:s.score,combo:s.combo,clearsSinceMiss:s.clearsSinceMiss,turn:s.turn,playerScores:s.playerScores,seed:s.seed,over:s.over};}
  function render(){renderBoard();renderTray();els.score.textContent=state.score.toLocaleString();els.combo.textContent=state.combo?`×${state.combo}`:'—';els.best.textContent=Math.max(state.score,Number(localStorage.getItem(bestKey())||0)).toLocaleString();els.deselect.classList.toggle('hidden',state.selected===null);if(state.mode!=='solo'){els.playerOne.classList.toggle('active',state.turn===0);els.playerTwo.classList.toggle('active',state.turn===1);els.playerOne.querySelector('b').textContent=state.playerScores[0];els.playerTwo.querySelector('b').textContent=state.playerScores[1];els.turnLabel.textContent=state.mode==='online'?(onlineSession?.status==='waiting'?'Room ready':state.turn===onlineSession?.playerIndex?'Your turn':'Their turn'):`${state.turn?'Megan':'George'}’s turn`;}}
  function renderBoard(){els.board.innerHTML='';for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const cell=document.createElement('button');cell.className='cell';cell.setAttribute('role','gridcell');if(state.board[r][c]){cell.classList.add('filled');cell.style.setProperty('--cell-color',state.board[r][c]);}cell.addEventListener('click',()=>place(r,c));cell.addEventListener('pointerenter',()=>preview(r,c));els.board.appendChild(cell);}}
  function renderTray(){els.tray.innerHTML='';state.tray.forEach((piece,i)=>{const button=document.createElement('button');button.className='piece';button.style.setProperty('--piece-color',piece.color);button.setAttribute('aria-label',`Shape ${i+1}`);if(piece.used)button.classList.add('used');if(state.selected===i)button.classList.add('selected');const rows=Math.max(...piece.shape.map(p=>p[0]))+1,cols=Math.max(...piece.shape.map(p=>p[1]))+1,grid=document.createElement('span');grid.className='mini-grid';grid.style.gridTemplateColumns=`repeat(${cols},1fr)`;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const dot=document.createElement('i');dot.className='mini-cell';if(piece.shape.some(p=>p[0]===r&&p[1]===c))dot.classList.add('on');grid.appendChild(dot);}button.appendChild(grid);button.addEventListener('click',()=>{if(piece.used)return;state.selected=state.selected===i?null:i;render();});els.tray.appendChild(button);});}
  const cellAt=(r,c)=>els.board.children[r*SIZE+c];function clearPreview(){document.querySelectorAll('.cell.preview').forEach(c=>c.classList.remove('preview'));}function preview(row,col){clearPreview();const piece=state.tray[state.selected];if(!piece||!canPlace(state,piece,row,col))return;piece.shape.forEach(([r,c])=>{const cell=cellAt(row+r,col+c);cell.classList.add('preview');cell.style.setProperty('--piece-color',piece.color);});}function flashInvalid(piece,row,col){piece.shape.forEach(([r,c])=>{if(row+r<SIZE&&col+c<SIZE){const cell=cellAt(row+r,col+c);cell.classList.add('invalid');setTimeout(()=>cell.classList.remove('invalid'),450);}});if(navigator.vibrate)navigator.vibrate(25);}function showToast(text){els.toast.textContent=text;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),900);}function saveBest(){const key=bestKey();if(state.score>Number(localStorage.getItem(key)||0))localStorage.setItem(key,state.score);}
  function endGame(){saveBest();$('#modalEyebrow').textContent='Board complete';$('#modalTitle').textContent=(state.mode==='race'||state.mode==='online')?(state.playerScores[0]===state.playerScores[1]?'Perfect tie':`${state.playerScores[0]>state.playerScores[1]?'George':'Megan'} wins`):'Beautifully played';$('#modalBody').textContent=(state.mode==='race'||state.mode==='online')?`Final score: ${state.playerScores[0]}–${state.playerScores[1]}.`:`You built a score of ${state.score.toLocaleString()}.`;els.modal.classList.add('open');}
  function leaveOnline(){onlineSession?.unsubscribe?.();onlineSession=null;history.replaceState(null,'',location.pathname);}
  function goHome(){leaveOnline();els.game.classList.remove('active');els.home.classList.add('active');els.modal.classList.remove('open');}
  function roomCode(){return Array.from({length:6},()=>CODE_CHARS[Math.floor(Math.random()*CODE_CHARS.length)]).join('');}
  function normalizeCode(value){return value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);}
  async function loadFirebase(){const config=window.MOSAIC_FIREBASE_CONFIG;if(!config)throw new Error('Online rooms are built but the dedicated Firebase project still needs connecting.');if(!firebasePromise)firebasePromise=Promise.all([import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js')]).then(([appApi,authApi,databaseApi])=>{const app=appApi.initializeApp(config);return{authApi,databaseApi,auth:authApi.getAuth(app),db:databaseApi.getDatabase(app)};});const firebase=await firebasePromise;if(!firebase.auth.currentUser)await firebase.authApi.signInAnonymously(firebase.auth);return firebase;}
  async function createRoom(){const firebase=await loadFirebase();let code,ref;for(let tries=0;tries<8;tries++){code=roomCode();ref=firebase.databaseApi.ref(firebase.db,`rooms/${code}`);if(!(await firebase.databaseApi.get(ref)).exists())break;}const initial=newState('online');await firebase.databaseApi.set(ref,{hostUid:firebase.auth.currentUser.uid,status:'waiting',createdAt:firebase.databaseApi.serverTimestamp(),state:serializable(initial)});beginOnline(firebase,ref,code,0,'waiting',initial);}
  async function joinRoom(){const code=normalizeCode(els.roomCodeInput.value);if(code.length!==6)throw new Error('Enter the six-character code from the other iPad.');const firebase=await loadFirebase(),ref=firebase.databaseApi.ref(firebase.db,`rooms/${code}`),snap=await firebase.databaseApi.get(ref);if(!snap.exists())throw new Error('That room could not be found.');const room=snap.val();if(room.status!=='waiting'||room.guestUid)throw new Error('That room already has two players.');await firebase.databaseApi.set(firebase.databaseApi.child(ref,'guestUid'),firebase.auth.currentUser.uid);await firebase.databaseApi.set(firebase.databaseApi.child(ref,'status'),'playing');beginOnline(firebase,ref,code,1,'playing',normalizeState(room.state));}
  function beginOnline(firebase,roomRef,code,playerIndex,status,initial){onlineSession?.unsubscribe?.();onlineSession={firebase,roomRef,code,playerIndex,status,unsubscribe:null};history.replaceState(null,'',`${location.pathname}?room=${code}`);start('online',normalizeState(initial));onlineSession.unsubscribe=firebase.databaseApi.onValue(roomRef,snap=>{if(!snap.exists()){els.roomStatusText.textContent='Room closed';return;}const room=snap.val();onlineSession.status=room.status;state=normalizeState(room.state);els.roomStatusText.textContent=room.status==='waiting'?`ROOM ${code} · Waiting for Megan…`:`ROOM ${code} · ${state.turn===playerIndex?'Your turn':'Their turn'}`;render();if(state.over)endGame();});}
  function inviteUrl(){return onlineSession?`${location.origin}${location.pathname}?room=${onlineSession.code}`:location.href;}
  async function copyInvite(){if(!onlineSession)return;await navigator.clipboard.writeText(onlineSession.code);showToast('Room code copied');}
  async function shareInvite(){if(!onlineSession)return;const data={title:'Join my Mosaic Mates room',text:`Join my Mosaic Mates room ${onlineSession.code}`,url:inviteUrl()};if(navigator.share){try{await navigator.share(data);return;}catch(error){if(error?.name==='AbortError')return;}}try{await navigator.clipboard.writeText(inviteUrl());showToast('Invite link copied');}catch{showToast('Could not share this invite');}}
  function setOnlineAction(action){onlineAction=action;document.querySelectorAll('[data-online-action]').forEach(b=>b.classList.toggle('active',b.dataset.onlineAction===action));els.roomCodeField.classList.toggle('hidden',action!=='join');els.onlineStart.textContent=action==='join'?'Join private room':'Create private room';els.onlineError.textContent='';}
  document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mode)));$('#backButton').addEventListener('click',goHome);$('#restartButton').addEventListener('click',()=>state.mode==='online'?showToast('Online rematch comes next'):start(state.mode));$('#playAgain').addEventListener('click',()=>start(state.mode));$('#modalHome').addEventListener('click',goHome);els.deselect.addEventListener('click',()=>{state.selected=null;render();});els.board.addEventListener('pointerleave',clearPreview);
  $('#onlinePreview').addEventListener('click',()=>{els.onlineModal.classList.add('open');els.onlineModal.setAttribute('aria-hidden','false');setOnlineAction('create');});$('#closeOnline').addEventListener('click',()=>els.onlineModal.classList.remove('open'));document.querySelectorAll('[data-online-action]').forEach(b=>b.addEventListener('click',()=>setOnlineAction(b.dataset.onlineAction)));els.roomCodeInput.addEventListener('input',()=>els.roomCodeInput.value=normalizeCode(els.roomCodeInput.value));els.onlineStart.addEventListener('click',async()=>{els.onlineError.textContent='';els.onlineStart.disabled=true;els.onlineStart.textContent='Connecting…';try{if(onlineAction==='create')await createRoom();else await joinRoom();}catch(error){els.onlineError.textContent=error.message;setOnlineAction(onlineAction);}finally{els.onlineStart.disabled=false;}});$('#copyRoomCode').addEventListener('click',copyInvite);$('#shareRoom').addEventListener('click',shareInvite);
  const linked=normalizeCode(new URLSearchParams(location.search).get('room')||'');if(linked){els.onlineModal.classList.add('open');setOnlineAction('join');els.roomCodeInput.value=linked;}if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
})();
